---
# tasks file for user
#
- name: Add the user 'eduard' with a specific uid and a primary group of 'wheel'
  ansible.builtin.user:
    name: eduard
    comment: Ed Borec
    uid: 1040
    group: wheel
