---
# tasks file for user
#
- name: Add the user 'eduard' with a specific uid and a primary group of 'wheel'
  ansible.builtin.user:
    name: eduard
    comment: Ed Borec
    uid: 1040
    group: wheel

- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
  when: ansible_default_ipv4.gateway is defined

- name: Get uptime information
  ansible.builtin.shell: /usr/bin/uptime
  register: result
  
  debug:
    msg: "{{result.stdout}}"
